### ISSUE TITLE
Save predictions as jpg

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#18]
Save figure flag in the detector has not been implemented yet. With an argument similar to display_detection, allow an argument for save figure or save prediction.

**Comment by ShreyPandit** [comment]
I would like to take up this issue. Kindly guide how to proceed.

**Comment by ashwinvaswani** [comment]
In detect_players_image method, add another argument which is False by default and when True, saves the prediction plot as jpg/png and prints a message.
