### ISSUE TITLE
Plain court template for heatmap

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#34]
Currently, the heatmap base image contains the players too. We would like to have a base template court of the same size as the wrapped transform(see dimensions of heatmap.png) and show heatmap on that rather than a court image with players. 
Eg: If we can have a pure white image with just badminton court "white" lines in black as base image, that would be good to show the heatmap on. We can explore other colors and black/neon color scenes later

**Comment by Sharanranjit** [comment]
For this I was wondering if we can get the court through hough transform and grabcut algo as done in this [paper](https://arxiv.org/pdf/1511.08522.pdf)(Secion 4.1) by the same author. This will help in avoiding the user input for court coordinates and we can maintain this template throughout.
But I was failing multiple times in hough transform to get the courts borders. If anyone has any suggestion regarding this, please feel free to share.

**Comment by ashwinvaswani** [comment]
The current extraction based on the manual input is this:
https://drive.google.com/open?id=1nAi3SaP1fFYBf4lT1afYhjkorCveGrju

@Sharanranjit  Can we explain what issues were you facing with the Hough transform?
Would you like to take up this issue?

**Comment by Sharanranjit** [comment]
I am not sure yet and the image you linked seems fine for our approach
But I was just curious whether we can avoid the input coordinates from the user for each video. 
Also, for some reason my opencv windows don't work properly like imshow, setMouseCallback, etc. Might be some issue in my cv installation.
But ya, I was just exploring an alternate way for generating heatmaps.
The issue with [Hough transform](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html)(the link I referred) is that its not detecting the white border lines from the image.

**Comment by Sharanranjit** [comment]
I am not sure yet and the image you linked seems fine for our approach
But I was just curious whether we can avoid the input coordinates from the user for each video.
But ya, I was just exploring an alternate way for generating heatmaps.
The issue with [Hough transform](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html)(the link I referred) is that its not detecting the white border lines from the image.

**Comment by Sharanranjit** [comment]
Oh, I am not sure yet. I was just exploring an alternate way to generate heat maps as we are depending on the user to input court coordinates. Was curious whether we can avoid that.
Regarding Hough transform, I could'nt come up with right number of lines as the image has various redundant lines. Check out this fig. Do you think its necessary or can we just continue with user input?

![image](https://user-images.githubusercontent.com/40764332/82090064-7668b300-9712-11ea-8abf-7310bf3cd0d0.png)

**Comment by Sharanranjit** [comment]
Yep, I can take up this issue now. Will share a screenshot soon

**Comment by ashwinvaswani** [comment]
Sure!

**Comment by Sharanranjit** [comment]
Can you verify if this is fine? I made the all pixels at column mid white, to represent the net.
It was kinda trial and error values i used for dilation and erosion, but works fine for most images.
![image](https://user-images.githubusercontent.com/40764332/82128531-77b0e300-97d9-11ea-9192-c93e429314b3.png)

**Comment by ashwinvaswani** [comment]
That's great! Send a PR. Currently result for transform is used as base image for heatmap. Change it to this and for center bottom coordinates use any neon/bright colour.
