### ISSUE TITLE
Progress bar and ETA for getting predictions

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#35]
For the get_heatmap and detect_players_video methods, create a progress bar/ show ETA dynamically so that the user can know how much time before the entire video will be processed.

**Comment by rajanarasimhan** [comment]
Bhaiya I will try this

**Comment by ashwinvaswani** [comment]
Sure. With the latest merge, we are no more rendering the display for heatmap and detect players video, so we want to have a progress bar / ETA so that the user can know how much time left till it gets processed. So you can check time taken by detector for processing 1 frame/ 1 second of video and interpolate that to print ETA at first. Then you can enhance it by adding a progress bar
