### ISSUE TITLE
Documentation for heatmap

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#36]
Add docs for heatmap generations and usage

**Comment by AmoghSinha** [comment]
I'd like to take this issue.

**Comment by ashwinvaswani** [comment]
Sure. Kindly run the heatmap thing once using the chunk of code in the README and add the required documentation in Docs/Badminton.py as per it's format!

**Comment by ashwinvaswani** [comment]
It's been done already! Kindly take up another issue.
