### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by Rijul1999** [SforAiDl/Playground#44]
Run the code, after making the changes mentioned in the README for the Windows operating system, and verify that everything is working as intended. If there is some error anywhere submit a new issue.

**Comment by rajanarasimhan** [comment]
Can I take this issue as I primarily use windows with Linux subsystem?

**Comment by Rijul1999** [comment]
Yup feel free

**Comment by rajanarasimhan** [comment]
should I test this in Anaconda prompt??

**Comment by Rijul1999** [comment]
yup

**Comment by rajanarasimhan** [comment]
It works perfectly in the Anaconda prompt

**Comment by Rijul1999** [comment]
Great
