### ISSUE TITLE
yolov3-tiny.cfg file missing

### ISSUE THREAD

**Issue by someshsingh22** [SforAiDl/Playground#48]
The tiny yolo module has been implemented but the cfg file is not downloaded

```python
obj = Detector(tiny=True)

/content/Playground/Badminton/utilities/parse_config.py in parse_model_config(path)
      1 def parse_model_config(path):
      2     """Parses the yolo-v3 layer configuration file and returns module definitions"""
----> 3     file = open(path, "r")
      4     lines = file.read().split("\n")
      5     lines = [x for x in lines if x and not x.startswith("#")]

FileNotFoundError: [Errno 2] No such file or directory: 'Badminton/config/yolov3-tiny.cfg'
```

**Comment by jaygala** [comment]
Actually, I have the yolov3-tiny.cfg on my forked repo - https://github.com/jaygala/Playground
Please find it here. I am not sure if I can add this file in the main SforAiDl repo

**Comment by someshsingh22** [comment]
@jaygala Then please add it to the repo, In case you are facing merge problems make sure you have added the main repo as an upstream, pull the upstream and make a PR
