### ISSUE TITLE
Data processing to extract annotations

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#52]
The dataset has been uploaded. We'll need to extract frames and annotations and prepare the directory format for our models. The eaf files contain the starting and ending points of actions along with their annotations. Since there are multiple eaf files, I'd suggest taking up one video/eaf file and processing that first to understand if your code is working fine. Please download the video files themselves from YouTube, since they are too large by themselves to be added to the repository. The expected Directory structure after processing is:

-Data
-------train
-------------smash
---------------------clip1
-----------------------------frame1
-----------------------------frame2
-----------------------------frame3
-----------------------------and so on
---------------------clip2
-----------------------------frame1
-----------------------------frame2
-----------------------------frame3
-----------------------------and so on
-------------lob and so on

-------val
------------Similarly

**Comment by mahakkothari** [comment]
why are there two TIME_SLOT_REF in Tier1?

**Comment by ashwinvaswani** [comment]
Because tier1 has actions and actions are temporal and are between two timestamps. Check annotation_style file

**Comment by mahakkothari** [comment]
Got it, thanks!
