### ISSUE TITLE
Removing code redundancy

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#57]
Badminton.py has a lot of redundant code in terms of checks and if-else statements. 
For example:
```
if optimization==True:
            frames_skipped=frames_skipped_input
        else:
            frames_skipped=1
if optimization==True:
     count_of_frames=0
      .. and so on
```
Such scenarios can be removed and code can be optimised further

**Comment by siddharth2411** [comment]
Hi, I have been working on this issue. I will soon finish it and send a PR.

**Comment by ashwinvaswani** [comment]
Sure
