### ISSUE TITLE
Code modularisation

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#58]
Create helper functions in utils.py for modularising the code in badminton.py. Currently, the code seems a little too cluttered and congested.

**Comment by samruddhibothara** [comment]
I'd like to take this up

**Comment by samruddhibothara** [comment]
I've moved the helper functions. What else should I modularize?

**Comment by ashwinvaswani** [comment]
The code is pretty redundant for video detector and heatmap. Can create helper functions for the redundant code and just call them in the two methods.
