### ISSUE TITLE
Extract position of feet of detected person

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#6]
The bottom center of the detected person must be extracted and returned which will be used for heatmap generation. Simply return those co-ordinates from the detect_players method.

**Comment by ShreyPandit** [comment]
I would like to take up this issue and give it a try.

**Comment by ashwinvaswani** [comment]
Sure, in the Badminton/Badminton.py, in the detect_players method, return a list consisting of bonding box co-ordinates and also create a method that takes in boxes co-ordinated and returns a list of "centre-bottom" co-ordinates for those boxes. It's a fairly simple task! Best of luck!
