### ISSUE TITLE
Downloading weights

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#8]
Currently weights need to be explicitly downloaded beforehand using the script config/download_weights.sh
Add necessary code in Detector in Badminton/Badminton.py to check if weights file has been downloaded, if no, download it within code and give error is weights cannot be downloaded(can happen due to network, space or some other issue)

**Comment by mahakkothari** [comment]
I have tried to resolve this issue.
I have sent a PR, please have a look at it

**Comment by ashwinvaswani** [comment]
Great! Merged
