### ISSUE TITLE
Implementing action segmentation

### ISSUE THREAD

**Issue by ashwinvaswani** [SforAiDl/Playground#84]
dataset extractor is complete. Work on action segmentation can be started

**Comment by Sharanranjit** [comment]
So just wanted some clarification:
Given a video, we need to segment the frames corresponding to the strokes(action) right? And it must be done for both players.
So as you suggested, we need to develop a 3D model, as we have temporal dimension.
Is there anything I'm missing or you have something else in your mind?

**Comment by ashwinvaswani** [comment]
@Sharanranjit There's another issue on this. I'm closing this one. I'm currently working on that one, let me know if you want to contribute to it.
